# Run and upload codecov report.

name: Tests and codecov.

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PLATFORM: GITHUB
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Test with pytest
        run: |
            python -m pip install pipenv
            pipenv install --deploy --dev
            pipenv run pytest
      - name: Build python package
        run: |
          python -m pip install setuptools wheel
          pipenv install
          python setup.py sdist bdist_wheel